# A job running SQL queries on a SQL warehouse
resources:
  jobs:
    sql_workflow_etl_crypto:
      name: sql_workflow_etl_crypto

      # Run this job every day, exactly one day from the last run; see https://docs.databricks.com/api/workspace/jobs/create#trigger
      schedule:
        quartz_cron_expression: "* 5 * * * ?"
        timezone_id: America/Sao_Paulo

      email_notifications:
        on_failure:
          - flavio.silva@clear.sale

      parameters:
        - name: catalog
          default: ${var.catalog}
        - name: bundle_target
          default: ${bundle.target}

      tasks:
        - task_key: bronze_deposit
          sql_task:
            warehouse_id: ${var.warehouse_id}
            file:
              path: ../jobs/bronze/deposit.sql
        - task_key: bronze_withdrawal
          sql_task:
            warehouse_id: ${var.warehouse_id}
            file:
              path: ../jobs/bronze/withdrawal.sql

        - task_key: silver_deposit
          depends_on:
            - task_key: bronze_deposit
          sql_task:
            warehouse_id: ${var.warehouse_id}
            file:
              path: ../jobs/silver/deposit.sql
              
        - task_key: silver_withdrawal
          depends_on:
            - task_key: bronze_withdrawal
          sql_task:
            warehouse_id: ${var.warehouse_id}
            file:
              path: ../jobs/silver/withdrawal.sql
